#!/bin/sh
mkdir osx/src
cp -R dist/JavaSim.app osx/src/
mkdir osx/src/.background
cp osx/background.png osx/src/.background/background.png
hdiutil create -srcfolder "osx/src" -volname "JavaSim" -fs HFS+ -fsargs "-c c=64,a=16,e=16" -format UDRW -size 10m "dist/pack.temp.dmg"
device=$(hdiutil attach -readwrite -noverify -noautoopen "dist/pack.temp.dmg" | egrep '^/dev/' | sed 1q | awk '{print $1}')
echo "Waiting 3 seconds after mount attempt."
sleep 3
echo '
   tell application "Finder"
     tell disk "JavaSim"
           open
           set current view of container window to icon view
           set toolbar visible of container window to false
           set statusbar visible of container window to false
           set the bounds of container window to {400, 100, 1040, 400}
           set theViewOptions to the icon view options of container window
           set arrangement of theViewOptions to not arranged
           set icon size of theViewOptions to 128
           set background picture of theViewOptions to file ".background:background.png"
           make new alias file at container window to POSIX file "/Applications" with properties {name:"Applications"}
           set position of item "Applications" of container window to {135, 125}
           set position of item "JavaSim" of container window to {508, 125}
           update without registering applications
           delay 5
           close
     end tell
   end tell
' | osascript
chmod -Rf go-w /Volumes/JavaSim
sync
sync
hdiutil detach ${device}
echo "Waiting 2 seconds after unmounting."
sleep 2
hdiutil convert "dist/pack.temp.dmg" -format UDZO -imagekey zlib-level=9 -o dist/JavaSim-$1.dmg
echo "Removing old pack.temp.dmg"
rm -f dist/pack.temp.dmg