// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/data_message.proto

package com.marklalor.javasim.proto;

public final class DataMessageProto {
  private DataMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DataMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:javasim.DataMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 session = 1;</code>
     */
    int getSession();

    /**
     * <code>sfixed64 msb = 2;</code>
     */
    long getMsb();

    /**
     * <code>sfixed64 lsb = 3;</code>
     */
    long getLsb();

    /**
     * <code>uint32 instance = 4;</code>
     */
    int getInstance();

    /**
     * <code>.javasim.DataMessage.DataType type = 7;</code>
     */
    int getTypeValue();
    /**
     * <code>.javasim.DataMessage.DataType type = 7;</code>
     */
    com.marklalor.javasim.proto.DataMessageProto.DataMessage.DataType getType();

    /**
     * <code>uint32 chunk = 5;</code>
     */
    int getChunk();

    /**
     * <code>uint32 chunks = 6;</code>
     */
    int getChunks();

    /**
     * <code>bytes data = 8;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code javasim.DataMessage}
   */
  public  static final class DataMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:javasim.DataMessage)
      DataMessageOrBuilder {
    // Use DataMessage.newBuilder() to construct.
    private DataMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DataMessage() {
      session_ = 0;
      msb_ = 0L;
      lsb_ = 0L;
      instance_ = 0;
      type_ = 0;
      chunk_ = 0;
      chunks_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private DataMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              session_ = input.readUInt32();
              break;
            }
            case 17: {

              msb_ = input.readSFixed64();
              break;
            }
            case 25: {

              lsb_ = input.readSFixed64();
              break;
            }
            case 32: {

              instance_ = input.readUInt32();
              break;
            }
            case 40: {

              chunk_ = input.readUInt32();
              break;
            }
            case 48: {

              chunks_ = input.readUInt32();
              break;
            }
            case 56: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 66: {

              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.marklalor.javasim.proto.DataMessageProto.internal_static_javasim_DataMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.marklalor.javasim.proto.DataMessageProto.internal_static_javasim_DataMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.marklalor.javasim.proto.DataMessageProto.DataMessage.class, com.marklalor.javasim.proto.DataMessageProto.DataMessage.Builder.class);
    }

    /**
     * Protobuf enum {@code javasim.DataMessage.DataType}
     */
    public enum DataType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>BOOLEAN = 0;</code>
       */
      BOOLEAN(0),
      /**
       * <code>BYTE = 1;</code>
       */
      BYTE(1),
      /**
       * <code>INT32 = 2;</code>
       */
      INT32(2),
      /**
       * <code>INT64 = 3;</code>
       */
      INT64(3),
      /**
       * <code>INT128 = 4;</code>
       */
      INT128(4),
      /**
       * <code>UTF8_TEXT = 5;</code>
       */
      UTF8_TEXT(5),
      /**
       * <code>PNG_IMAGE = 6;</code>
       */
      PNG_IMAGE(6),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>BOOLEAN = 0;</code>
       */
      public static final int BOOLEAN_VALUE = 0;
      /**
       * <code>BYTE = 1;</code>
       */
      public static final int BYTE_VALUE = 1;
      /**
       * <code>INT32 = 2;</code>
       */
      public static final int INT32_VALUE = 2;
      /**
       * <code>INT64 = 3;</code>
       */
      public static final int INT64_VALUE = 3;
      /**
       * <code>INT128 = 4;</code>
       */
      public static final int INT128_VALUE = 4;
      /**
       * <code>UTF8_TEXT = 5;</code>
       */
      public static final int UTF8_TEXT_VALUE = 5;
      /**
       * <code>PNG_IMAGE = 6;</code>
       */
      public static final int PNG_IMAGE_VALUE = 6;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataType valueOf(int value) {
        return forNumber(value);
      }

      public static DataType forNumber(int value) {
        switch (value) {
          case 0: return BOOLEAN;
          case 1: return BYTE;
          case 2: return INT32;
          case 3: return INT64;
          case 4: return INT128;
          case 5: return UTF8_TEXT;
          case 6: return PNG_IMAGE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DataType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DataType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
              public DataType findValueByNumber(int number) {
                return DataType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.marklalor.javasim.proto.DataMessageProto.DataMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final DataType[] VALUES = values();

      public static DataType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DataType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:javasim.DataMessage.DataType)
    }

    public static final int SESSION_FIELD_NUMBER = 1;
    private int session_;
    /**
     * <code>uint32 session = 1;</code>
     */
    public int getSession() {
      return session_;
    }

    public static final int MSB_FIELD_NUMBER = 2;
    private long msb_;
    /**
     * <code>sfixed64 msb = 2;</code>
     */
    public long getMsb() {
      return msb_;
    }

    public static final int LSB_FIELD_NUMBER = 3;
    private long lsb_;
    /**
     * <code>sfixed64 lsb = 3;</code>
     */
    public long getLsb() {
      return lsb_;
    }

    public static final int INSTANCE_FIELD_NUMBER = 4;
    private int instance_;
    /**
     * <code>uint32 instance = 4;</code>
     */
    public int getInstance() {
      return instance_;
    }

    public static final int TYPE_FIELD_NUMBER = 7;
    private int type_;
    /**
     * <code>.javasim.DataMessage.DataType type = 7;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.javasim.DataMessage.DataType type = 7;</code>
     */
    public com.marklalor.javasim.proto.DataMessageProto.DataMessage.DataType getType() {
      com.marklalor.javasim.proto.DataMessageProto.DataMessage.DataType result = com.marklalor.javasim.proto.DataMessageProto.DataMessage.DataType.valueOf(type_);
      return result == null ? com.marklalor.javasim.proto.DataMessageProto.DataMessage.DataType.UNRECOGNIZED : result;
    }

    public static final int CHUNK_FIELD_NUMBER = 5;
    private int chunk_;
    /**
     * <code>uint32 chunk = 5;</code>
     */
    public int getChunk() {
      return chunk_;
    }

    public static final int CHUNKS_FIELD_NUMBER = 6;
    private int chunks_;
    /**
     * <code>uint32 chunks = 6;</code>
     */
    public int getChunks() {
      return chunks_;
    }

    public static final int DATA_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 8;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (session_ != 0) {
        output.writeUInt32(1, session_);
      }
      if (msb_ != 0L) {
        output.writeSFixed64(2, msb_);
      }
      if (lsb_ != 0L) {
        output.writeSFixed64(3, lsb_);
      }
      if (instance_ != 0) {
        output.writeUInt32(4, instance_);
      }
      if (chunk_ != 0) {
        output.writeUInt32(5, chunk_);
      }
      if (chunks_ != 0) {
        output.writeUInt32(6, chunks_);
      }
      if (type_ != com.marklalor.javasim.proto.DataMessageProto.DataMessage.DataType.BOOLEAN.getNumber()) {
        output.writeEnum(7, type_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(8, data_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (session_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, session_);
      }
      if (msb_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSFixed64Size(2, msb_);
      }
      if (lsb_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSFixed64Size(3, lsb_);
      }
      if (instance_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, instance_);
      }
      if (chunk_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, chunk_);
      }
      if (chunks_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, chunks_);
      }
      if (type_ != com.marklalor.javasim.proto.DataMessageProto.DataMessage.DataType.BOOLEAN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, type_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, data_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.marklalor.javasim.proto.DataMessageProto.DataMessage)) {
        return super.equals(obj);
      }
      com.marklalor.javasim.proto.DataMessageProto.DataMessage other = (com.marklalor.javasim.proto.DataMessageProto.DataMessage) obj;

      boolean result = true;
      result = result && (getSession()
          == other.getSession());
      result = result && (getMsb()
          == other.getMsb());
      result = result && (getLsb()
          == other.getLsb());
      result = result && (getInstance()
          == other.getInstance());
      result = result && type_ == other.type_;
      result = result && (getChunk()
          == other.getChunk());
      result = result && (getChunks()
          == other.getChunks());
      result = result && getData()
          .equals(other.getData());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SESSION_FIELD_NUMBER;
      hash = (53 * hash) + getSession();
      hash = (37 * hash) + MSB_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMsb());
      hash = (37 * hash) + LSB_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLsb());
      hash = (37 * hash) + INSTANCE_FIELD_NUMBER;
      hash = (53 * hash) + getInstance();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + CHUNK_FIELD_NUMBER;
      hash = (53 * hash) + getChunk();
      hash = (37 * hash) + CHUNKS_FIELD_NUMBER;
      hash = (53 * hash) + getChunks();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.marklalor.javasim.proto.DataMessageProto.DataMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.marklalor.javasim.proto.DataMessageProto.DataMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.marklalor.javasim.proto.DataMessageProto.DataMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.marklalor.javasim.proto.DataMessageProto.DataMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.marklalor.javasim.proto.DataMessageProto.DataMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.marklalor.javasim.proto.DataMessageProto.DataMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.marklalor.javasim.proto.DataMessageProto.DataMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.marklalor.javasim.proto.DataMessageProto.DataMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.marklalor.javasim.proto.DataMessageProto.DataMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.marklalor.javasim.proto.DataMessageProto.DataMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.marklalor.javasim.proto.DataMessageProto.DataMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.marklalor.javasim.proto.DataMessageProto.DataMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.marklalor.javasim.proto.DataMessageProto.DataMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code javasim.DataMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:javasim.DataMessage)
        com.marklalor.javasim.proto.DataMessageProto.DataMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.marklalor.javasim.proto.DataMessageProto.internal_static_javasim_DataMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.marklalor.javasim.proto.DataMessageProto.internal_static_javasim_DataMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.marklalor.javasim.proto.DataMessageProto.DataMessage.class, com.marklalor.javasim.proto.DataMessageProto.DataMessage.Builder.class);
      }

      // Construct using com.marklalor.javasim.proto.DataMessageProto.DataMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        session_ = 0;

        msb_ = 0L;

        lsb_ = 0L;

        instance_ = 0;

        type_ = 0;

        chunk_ = 0;

        chunks_ = 0;

        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.marklalor.javasim.proto.DataMessageProto.internal_static_javasim_DataMessage_descriptor;
      }

      public com.marklalor.javasim.proto.DataMessageProto.DataMessage getDefaultInstanceForType() {
        return com.marklalor.javasim.proto.DataMessageProto.DataMessage.getDefaultInstance();
      }

      public com.marklalor.javasim.proto.DataMessageProto.DataMessage build() {
        com.marklalor.javasim.proto.DataMessageProto.DataMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.marklalor.javasim.proto.DataMessageProto.DataMessage buildPartial() {
        com.marklalor.javasim.proto.DataMessageProto.DataMessage result = new com.marklalor.javasim.proto.DataMessageProto.DataMessage(this);
        result.session_ = session_;
        result.msb_ = msb_;
        result.lsb_ = lsb_;
        result.instance_ = instance_;
        result.type_ = type_;
        result.chunk_ = chunk_;
        result.chunks_ = chunks_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.marklalor.javasim.proto.DataMessageProto.DataMessage) {
          return mergeFrom((com.marklalor.javasim.proto.DataMessageProto.DataMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.marklalor.javasim.proto.DataMessageProto.DataMessage other) {
        if (other == com.marklalor.javasim.proto.DataMessageProto.DataMessage.getDefaultInstance()) return this;
        if (other.getSession() != 0) {
          setSession(other.getSession());
        }
        if (other.getMsb() != 0L) {
          setMsb(other.getMsb());
        }
        if (other.getLsb() != 0L) {
          setLsb(other.getLsb());
        }
        if (other.getInstance() != 0) {
          setInstance(other.getInstance());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getChunk() != 0) {
          setChunk(other.getChunk());
        }
        if (other.getChunks() != 0) {
          setChunks(other.getChunks());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.marklalor.javasim.proto.DataMessageProto.DataMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.marklalor.javasim.proto.DataMessageProto.DataMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int session_ ;
      /**
       * <code>uint32 session = 1;</code>
       */
      public int getSession() {
        return session_;
      }
      /**
       * <code>uint32 session = 1;</code>
       */
      public Builder setSession(int value) {
        
        session_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 session = 1;</code>
       */
      public Builder clearSession() {
        
        session_ = 0;
        onChanged();
        return this;
      }

      private long msb_ ;
      /**
       * <code>sfixed64 msb = 2;</code>
       */
      public long getMsb() {
        return msb_;
      }
      /**
       * <code>sfixed64 msb = 2;</code>
       */
      public Builder setMsb(long value) {
        
        msb_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sfixed64 msb = 2;</code>
       */
      public Builder clearMsb() {
        
        msb_ = 0L;
        onChanged();
        return this;
      }

      private long lsb_ ;
      /**
       * <code>sfixed64 lsb = 3;</code>
       */
      public long getLsb() {
        return lsb_;
      }
      /**
       * <code>sfixed64 lsb = 3;</code>
       */
      public Builder setLsb(long value) {
        
        lsb_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sfixed64 lsb = 3;</code>
       */
      public Builder clearLsb() {
        
        lsb_ = 0L;
        onChanged();
        return this;
      }

      private int instance_ ;
      /**
       * <code>uint32 instance = 4;</code>
       */
      public int getInstance() {
        return instance_;
      }
      /**
       * <code>uint32 instance = 4;</code>
       */
      public Builder setInstance(int value) {
        
        instance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 instance = 4;</code>
       */
      public Builder clearInstance() {
        
        instance_ = 0;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.javasim.DataMessage.DataType type = 7;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.javasim.DataMessage.DataType type = 7;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.javasim.DataMessage.DataType type = 7;</code>
       */
      public com.marklalor.javasim.proto.DataMessageProto.DataMessage.DataType getType() {
        com.marklalor.javasim.proto.DataMessageProto.DataMessage.DataType result = com.marklalor.javasim.proto.DataMessageProto.DataMessage.DataType.valueOf(type_);
        return result == null ? com.marklalor.javasim.proto.DataMessageProto.DataMessage.DataType.UNRECOGNIZED : result;
      }
      /**
       * <code>.javasim.DataMessage.DataType type = 7;</code>
       */
      public Builder setType(com.marklalor.javasim.proto.DataMessageProto.DataMessage.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.javasim.DataMessage.DataType type = 7;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private int chunk_ ;
      /**
       * <code>uint32 chunk = 5;</code>
       */
      public int getChunk() {
        return chunk_;
      }
      /**
       * <code>uint32 chunk = 5;</code>
       */
      public Builder setChunk(int value) {
        
        chunk_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 chunk = 5;</code>
       */
      public Builder clearChunk() {
        
        chunk_ = 0;
        onChanged();
        return this;
      }

      private int chunks_ ;
      /**
       * <code>uint32 chunks = 6;</code>
       */
      public int getChunks() {
        return chunks_;
      }
      /**
       * <code>uint32 chunks = 6;</code>
       */
      public Builder setChunks(int value) {
        
        chunks_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 chunks = 6;</code>
       */
      public Builder clearChunks() {
        
        chunks_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 8;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 8;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 8;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:javasim.DataMessage)
    }

    // @@protoc_insertion_point(class_scope:javasim.DataMessage)
    private static final com.marklalor.javasim.proto.DataMessageProto.DataMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.marklalor.javasim.proto.DataMessageProto.DataMessage();
    }

    public static com.marklalor.javasim.proto.DataMessageProto.DataMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DataMessage>
        PARSER = new com.google.protobuf.AbstractParser<DataMessage>() {
      public DataMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new DataMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DataMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DataMessage> getParserForType() {
      return PARSER;
    }

    public com.marklalor.javasim.proto.DataMessageProto.DataMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_javasim_DataMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_javasim_DataMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%src/main/resources/data_message.proto\022" +
      "\007javasim\"\207\002\n\013DataMessage\022\017\n\007session\030\001 \001(" +
      "\r\022\013\n\003msb\030\002 \001(\020\022\013\n\003lsb\030\003 \001(\020\022\020\n\010instance\030" +
      "\004 \001(\r\022+\n\004type\030\007 \001(\0162\035.javasim.DataMessag" +
      "e.DataType\022\r\n\005chunk\030\005 \001(\r\022\016\n\006chunks\030\006 \001(" +
      "\r\022\014\n\004data\030\010 \001(\014\"a\n\010DataType\022\013\n\007BOOLEAN\020\000" +
      "\022\010\n\004BYTE\020\001\022\t\n\005INT32\020\002\022\t\n\005INT64\020\003\022\n\n\006INT1" +
      "28\020\004\022\r\n\tUTF8_TEXT\020\005\022\r\n\tPNG_IMAGE\020\006B/\n\033co" +
      "m.marklalor.javasim.protoB\020DataMessagePr" +
      "otob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_javasim_DataMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_javasim_DataMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_javasim_DataMessage_descriptor,
        new java.lang.String[] { "Session", "Msb", "Lsb", "Instance", "Type", "Chunk", "Chunks", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
